project:
  type: website

website:
  title: "Eric Mossotti"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projectsBlog.qmd
        text: "Plog"
      - about.qmd
    page-footer:
        center:
            - text: "Data Developments"

format:
  html:
    theme: darkly
    toc: true
    page-layout: full

editor: visual

