project:
  type: website
  output-dir: _site

website:
  title: "ericMossotti.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: bikeShare.qmd
        text: Bike Share
    page-footer:
        center:
            - text: "Data Analysis Portfolio"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

