project:
  type: website
  #output-dir:

website:
  title: "ericMossotti.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    page-footer:
        center:
            - text: "Data Analysis Portfolio"

format:
  html:
    theme: 
        - cosmo
        - styles.sass
   # theme: cosmo
   # css: styles.css
    toc: true
    page-layout: full

editor: visual

