project:
  type: website
    #site-url: https://ericMossotti.github.io/Bike_Share
#  output-dir: docs
#  execute: freeze: true

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projectsBlog.qmd
        text: "Project Blog"
      - about.qmd
    page-footer:
        center:
            - text: "Data Analysis Portfolio"

format:
  html:
    theme:
        light: morph
        dark: solar
    #    - styles.sass
   # theme: cosmo
   # css: styles.css
    toc: true
    page-layout: full

editor: visual

