project:
  type: website
  output-dir: docs

website:
  title: "ericMossotti.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: bikeShare.qmd
        text: Bike Share
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

