<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eric Mossotti">

<title>ericMossotti.github.io - BikeShare</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">ericMossotti.github.io</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./bikeShare.html" aria-current="page"> 
<span class="menu-text">Bike Share</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#filtering-data-smartly" id="toc-filtering-data-smartly" class="nav-link active" data-scroll-target="#filtering-data-smartly">Filtering Data, Smartly</a></li>
  <li><a href="#visualizations" id="toc-visualizations" class="nav-link" data-scroll-target="#visualizations">Visualizations</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">BikeShare</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Eric Mossotti </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="references" class="level4">
<h4 class="anchored" data-anchor-id="references">References:</h4>
<ul>
<li><p><span class="citation" data-cites="datalic">(<a href="#ref-datalic" role="doc-biblioref"><span>“Data License Agreement | Divvy Bikes,”</span> n.d.</a>)</span></p>
<ul>
<li><a href="https://divvybikes.com/data-license-agreement">Data License Agreement | Divvy Bikes</a></li>
</ul></li>
<li><p><span class="citation" data-cites="motivate">(<a href="#ref-motivate" role="doc-biblioref"><span>“MOTIVATE,”</span> n.d.</a>)</span></p>
<ul>
<li><a href="https://motivateco.com/">MOTIVATE (motivateco.com)</a></li>
</ul></li>
<li><p><span class="citation" data-cites="indexof">(<a href="#ref-indexof" role="doc-biblioref"><span>“Index of Bucket <span>"</span>Divvy-Tripdata<span>"</span>,”</span> n.d.</a>)</span></p>
<ul>
<li><a href="https://divvy-tripdata.s3.amazonaws.com/index.html">Index of bucket “divvy-tripdata”</a></li>
</ul></li>
<li><p><span class="citation" data-cites="whyduck">(<a href="#ref-whyduck" role="doc-biblioref"><span>“Why DuckDB,”</span> n.d.</a>)</span></p>
<ul>
<li><a href="https://duckdb.org/why_duckdb">Why DuckDB?</a></li>
</ul></li>
<li><p><span class="citation" data-cites="rforda">(<a href="#ref-rforda" role="doc-biblioref"><span>“R for Data Science (2e) - 22&nbsp; Arrow,”</span> n.d.</a>)</span></p>
<ul>
<li><a href="https://r4ds.hadley.nz/arrow" title="Arrow">R for Data Science: Chapter 22: Arrow</a></li>
</ul></li>
<li><p><span class="citation" data-cites="great-ci">(<a href="#ref-great-ci" role="doc-biblioref"><span>“Great-Circle Distance - Wikipedia,”</span> n.d.</a>)</span></p>
<ul>
<li><a href="https://en.wikipedia.org/wiki/Great-circle_distance" class="uri">https://en.wikipedia.org/wiki/Great-circle_distance</a></li>
</ul></li>
<li><p><span class="citation" data-cites="average2024">(<a href="#ref-average2024" role="doc-biblioref"><span>“Average Bicycle Speed <span></span> How Fast Do Cyclists Ride and What Affects Their Pace - BikingulTimate.com (UPDATE 👍)”</span> 2024</a>)</span></p>
<ul>
<li><a href="https://bikingultimate.com/average-bicycle-speed-how-fast-do-cyclists-ride-and-what-affects-their-pace/" class="uri">https://bikingultimate.com/average-bicycle-speed-how-fast-do-cyclists-ride-and-what-affects-their-pace/</a></li>
</ul></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   success status_code resumefrom
1     TRUE         200          0
2     TRUE         200          0
3     TRUE         200          0
4     TRUE         200          0
5     TRUE         200          0
6     TRUE         200          0
7     TRUE         200          0
8     TRUE         200          0
9     TRUE         200          0
10    TRUE         200          0
11    TRUE         200          0
12    TRUE         200          0
                                                                 url
1  https://divvy-tripdata.s3.amazonaws.com/202301-divvy-tripdata.zip
2  https://divvy-tripdata.s3.amazonaws.com/202302-divvy-tripdata.zip
3  https://divvy-tripdata.s3.amazonaws.com/202303-divvy-tripdata.zip
4  https://divvy-tripdata.s3.amazonaws.com/202304-divvy-tripdata.zip
5  https://divvy-tripdata.s3.amazonaws.com/202305-divvy-tripdata.zip
6  https://divvy-tripdata.s3.amazonaws.com/202306-divvy-tripdata.zip
7  https://divvy-tripdata.s3.amazonaws.com/202307-divvy-tripdata.zip
8  https://divvy-tripdata.s3.amazonaws.com/202308-divvy-tripdata.zip
9  https://divvy-tripdata.s3.amazonaws.com/202309-divvy-tripdata.zip
10 https://divvy-tripdata.s3.amazonaws.com/202310-divvy-tripdata.zip
11 https://divvy-tripdata.s3.amazonaws.com/202311-divvy-tripdata.zip
12 https://divvy-tripdata.s3.amazonaws.com/202312-divvy-tripdata.zip
                             destfile error            type            modified
1  tempZips/202301-divvy-tripdata.zip  &lt;NA&gt; application/zip 2023-02-07 19:58:38
2  tempZips/202302-divvy-tripdata.zip  &lt;NA&gt; application/zip 2023-03-07 22:28:12
3  tempZips/202303-divvy-tripdata.zip  &lt;NA&gt; application/zip 2023-04-06 20:38:59
4  tempZips/202304-divvy-tripdata.zip  &lt;NA&gt; application/zip 2023-05-04 19:43:25
5  tempZips/202305-divvy-tripdata.zip  &lt;NA&gt; application/zip 2023-06-08 22:17:13
6  tempZips/202306-divvy-tripdata.zip  &lt;NA&gt; application/zip 2023-07-13 21:22:44
7  tempZips/202307-divvy-tripdata.zip  &lt;NA&gt; application/zip 2023-08-14 12:28:28
8  tempZips/202308-divvy-tripdata.zip  &lt;NA&gt; application/zip 2023-10-12 05:35:18
9  tempZips/202309-divvy-tripdata.zip  &lt;NA&gt; application/zip 2023-10-12 05:35:18
10 tempZips/202310-divvy-tripdata.zip  &lt;NA&gt; application/zip 2023-11-13 16:38:10
11 tempZips/202311-divvy-tripdata.zip  &lt;NA&gt; application/zip 2023-12-05 18:28:19
12 tempZips/202312-divvy-tripdata.zip  &lt;NA&gt; application/zip 2024-01-04 19:48:23
       time
1  0.949237
2  0.940734
3  1.038178
4  1.161054
5  1.377657
6  1.429683
7  1.732399
8  1.798923
9  1.965646
10 1.471834
11 1.774590
12 1.459267
                                                                                                                                                                                                                                                                                                                                                                                                                                               headers
1     HTTP/1.1 200 OK, x-amz-id-2: OJ7GBXNACsIyYhJHz/yUjT0LOy5OHSXZ7ONspXtPTpwU4ERQZQ/22Kqa+npeFAcOxWPgqFqcn8tMMoTxdAHsW+fOQp4joEmiitKtlWMC6+c=, x-amz-request-id: T8PHCSVSR51YB7TW, Date: Wed, 13 Mar 2024 07:09:44 GMT, Last-Modified: Tue, 07 Feb 2023 19:58:38 GMT, ETag: "9d7eeac61d737e017fd33856998aa65c", x-amz-server-side-encryption: AES256, Accept-Ranges: bytes, Content-Type: application/zip, Server: AmazonS3, Content-Length: 6776711
2     HTTP/1.1 200 OK, x-amz-id-2: LnFxa3h80CXvgn4/QUhTC2w2FG/ysCJRCbRt97lI8sCYcsye3VVVblb+J+wgnjSvIs4SU3ixC4d/MdFScMl9q/+ftkOqIVka6uxZHsKl+Tw=, x-amz-request-id: T8PHYNNQK0S1J2B4, Date: Wed, 13 Mar 2024 07:09:44 GMT, Last-Modified: Tue, 07 Mar 2023 22:28:12 GMT, ETag: "4da6b8b19f08c6a4150c49a8a9c32053", x-amz-server-side-encryption: AES256, Accept-Ranges: bytes, Content-Type: application/zip, Server: AmazonS3, Content-Length: 7081095
3    HTTP/1.1 200 OK, x-amz-id-2: R8iUwsAvepNrXMKfkOyGCux+YdUOh6TefkVpIB+P523LVAaMuLEEIlS2tASMFilBLDOBKq9jIS0kFR/86QM+7zXcL45q91XQzhkiZhex3sI=, x-amz-request-id: T8PRS1S5NPE0TPBS, Date: Wed, 13 Mar 2024 07:09:44 GMT, Last-Modified: Thu, 06 Apr 2023 20:38:59 GMT, ETag: "98cd34dd5e0cacc00f0695b7b5bc021c", x-amz-server-side-encryption: AES256, Accept-Ranges: bytes, Content-Type: application/zip, Server: AmazonS3, Content-Length: 10265597
4    HTTP/1.1 200 OK, x-amz-id-2: yMtIrZusJNkURcceLOwqO8pYTcE7pcKRzcV7IjPNgIlsrvAEwUXzHq+67bsirDV+tQSFlh7eCEK6fO64/w+5v3fFI7Ck5pR5u0dxIsVBHf4=, x-amz-request-id: T8PR00GTRX99TR0N, Date: Wed, 13 Mar 2024 07:09:44 GMT, Last-Modified: Thu, 04 May 2023 19:43:25 GMT, ETag: "2823f262b184589b31e04a5a5b16cb81", x-amz-server-side-encryption: AES256, Accept-Ranges: bytes, Content-Type: application/zip, Server: AmazonS3, Content-Length: 15398190
5  HTTP/1.1 200 OK, x-amz-id-2: 2s3llKjfQIJKabkySuD758B4tocBQ8eDJosKOTebkOXrtoF9W4yNjQ/gwdjKrLOsE6H/FegetSIOz5w+m/1yvGERPaccpvWOjF1y0oo6J+k=, x-amz-request-id: T8PNHT5BT5EG37DV, Date: Wed, 13 Mar 2024 07:09:44 GMT, Last-Modified: Thu, 08 Jun 2023 22:17:13 GMT, ETag: "fde45f27b7a2ec06da3e371e3c62d285-2", x-amz-server-side-encryption: AES256, Accept-Ranges: bytes, Content-Type: application/zip, Server: AmazonS3, Content-Length: 23442906
6  HTTP/1.1 200 OK, x-amz-id-2: OmVrnzKsDbbALXlWNGociJAinNtDNz5HXkTkXElCiqLS4SlBagWt3C1txcG6Ll1l5NwIrcsopgoatmtIwTXIZneCVMp1UA/GS2oh+U3WYVU=, x-amz-request-id: T8PZHX2902J0DXNY, Date: Wed, 13 Mar 2024 07:09:44 GMT, Last-Modified: Thu, 13 Jul 2023 21:22:44 GMT, ETag: "1ddfdb0ce7870e5f7eeacec67e9af3e6-2", x-amz-server-side-encryption: AES256, Accept-Ranges: bytes, Content-Type: application/zip, Server: AmazonS3, Content-Length: 25661651
7  HTTP/1.1 200 OK, x-amz-id-2: UhkwFYVnMps6l7FpNNXEoOQDP40PidW/dDZ5qjcktEMdRvJPI/XF8uf8PXckyGGcukGdnEg3j07BwiM1ETZ8EfwiwAaGfCXlhR+/9fzqoMs=, x-amz-request-id: GAB0RGZ2GYZJ64KP, Date: Wed, 13 Mar 2024 07:09:45 GMT, Last-Modified: Mon, 14 Aug 2023 12:28:28 GMT, ETag: "ba6c166bf9580f19206779cb16293fec-2", x-amz-server-side-encryption: AES256, Accept-Ranges: bytes, Content-Type: application/zip, Server: AmazonS3, Content-Length: 28544756
8  HTTP/1.1 200 OK, x-amz-id-2: SsWJsIIHsPgfBw+quY2tJCJPqo093fpxyjPN2dTPNR+HnOw2QYqty7QgKNfJ6sQNm1tHLePqgS8xjTwfpvtUKlCEHIEioJmZVUq6KQY44H0=, x-amz-request-id: GABEJAKJE3K553Y1, Date: Wed, 13 Mar 2024 07:09:45 GMT, Last-Modified: Thu, 12 Oct 2023 05:35:18 GMT, ETag: "28978e1c05a960d20b6288279ee2bd10-2", x-amz-server-side-encryption: AES256, Accept-Ranges: bytes, Content-Type: application/zip, Server: AmazonS3, Content-Length: 28649391
9  HTTP/1.1 200 OK, x-amz-id-2: chejkmyyY3Y+1uaOyyfYvniorlzAPomdb9QzI18G1UqekBPhUpM1waySnS+8X9iP1uecmIfcYgBJlc+uBooxOKb2sR1SWkXklEn6f3WmODY=, x-amz-request-id: GAB7MX0T4TWCQ0G7, Date: Wed, 13 Mar 2024 07:09:45 GMT, Last-Modified: Thu, 12 Oct 2023 05:35:18 GMT, ETag: "34ac0b42f90a23d313e7b34a8f8a2ae7-2", x-amz-server-side-encryption: AES256, Accept-Ranges: bytes, Content-Type: application/zip, Server: AmazonS3, Content-Length: 24894104
10 HTTP/1.1 200 OK, x-amz-id-2: IkL357fWFw5uIdjlU3QtotiJIJWfAQkmE0OI5OVUzz1VieJxAOBbbD/Zq6ZSk18llpGCI1kAlJWPDaqgwwBnmRM1XhsIzVfkEsYC/M+xkgw=, x-amz-request-id: GAB1WDVP45D587XZ, Date: Wed, 13 Mar 2024 07:09:45 GMT, Last-Modified: Mon, 13 Nov 2023 16:38:10 GMT, ETag: "3db172565a038398a6e9cd8dfe044f43-2", x-amz-server-side-encryption: AES256, Accept-Ranges: bytes, Content-Type: application/zip, Server: AmazonS3, Content-Length: 19145928
11   HTTP/1.1 200 OK, x-amz-id-2: L/Z5OmduGwSXbrI+jaNrz+LUjLBURLz6BKNk6s7Fa72a9kkY5zhzETWrFXb3KagfZbKF7fbbyr93BHsRRu/34D64Wx1mTS+vePXlyj31u4U=, x-amz-request-id: GAB6WDM75PRW7N7F, Date: Wed, 13 Mar 2024 07:09:45 GMT, Last-Modified: Tue, 05 Dec 2023 18:28:19 GMT, ETag: "af1e60148a489c910dc9687f7134b35d", x-amz-server-side-encryption: AES256, Accept-Ranges: bytes, Content-Type: application/zip, Server: AmazonS3, Content-Length: 13165411
12    HTTP/1.1 200 OK, x-amz-id-2: ECEcV8j9NaF4041xqQNTXGt2nQlow79JxeimocQiVzzOh5imafb/eLrKcwXMqbqCk+R5Ca6cxJaxj3b2oqXcX+v1lO9Lkum4uFMwdCluVz4=, x-amz-request-id: GABE12Y48H60SG2M, Date: Wed, 13 Mar 2024 07:09:45 GMT, Last-Modified: Thu, 04 Jan 2024 19:48:23 GMT, ETag: "ddeeab2d6668fe482553965334bf060f", x-amz-server-side-encryption: AES256, Accept-Ranges: bytes, Content-Type: application/zip, Server: AmazonS3, Content-Length: 8419815</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 4
   URLs                       `Zip File Paths` `File Names` `Parquet File Paths`
   &lt;chr&gt;                      &lt;chr&gt;            &lt;chr&gt;        &lt;chr&gt;               
 1 https://divvy-tripdata.s3… tempZips/202301… 202301-divv… tempFiles/202301-di…
 2 https://divvy-tripdata.s3… tempZips/202302… 202302-divv… tempFiles/202302-di…
 3 https://divvy-tripdata.s3… tempZips/202303… 202303-divv… tempFiles/202303-di…
 4 https://divvy-tripdata.s3… tempZips/202304… 202304-divv… tempFiles/202304-di…
 5 https://divvy-tripdata.s3… tempZips/202305… 202305-divv… tempFiles/202305-di…
 6 https://divvy-tripdata.s3… tempZips/202306… 202306-divv… tempFiles/202306-di…
 7 https://divvy-tripdata.s3… tempZips/202307… 202307-divv… tempFiles/202307-di…
 8 https://divvy-tripdata.s3… tempZips/202308… 202308-divv… tempFiles/202308-di…
 9 https://divvy-tripdata.s3… tempZips/202309… 202309-divv… tempFiles/202309-di…
10 https://divvy-tripdata.s3… tempZips/202310… 202310-divv… tempFiles/202310-di…
11 https://divvy-tripdata.s3… tempZips/202311… 202311-divv… tempFiles/202311-di…
12 https://divvy-tripdata.s3… tempZips/202312… 202312-divv… tempFiles/202312-di…</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Files now in tempFiles:  

 tempFiles/part-0.parquet</code></pre>
</div>
</div>
<p>might need to fix format below?</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,331,707 × 14
   ride_id          rideable_type started_at          ended_at           
   &lt;chr&gt;            &lt;chr&gt;         &lt;dttm&gt;              &lt;dttm&gt;             
 1 F96D5A74A3E41399 electric_bike 2023-01-21 20:05:42 2023-01-21 20:16:33
 2 13CB7EB698CEDB88 classic_bike  2023-01-10 15:37:36 2023-01-10 15:46:05
 3 BD88A2E670661CE5 electric_bike 2023-01-02 07:51:57 2023-01-02 08:05:11
 4 C90792D034FED968 classic_bike  2023-01-22 10:52:58 2023-01-22 11:01:44
 5 3397017529188E8A classic_bike  2023-01-12 13:58:01 2023-01-12 14:13:20
 6 58E68156DAE3E311 electric_bike 2023-01-31 07:18:03 2023-01-31 07:21:16
 7 2F7194B6012A98D4 electric_bike 2023-01-15 21:18:36 2023-01-15 21:32:36
 8 DB1CF84154D6A049 classic_bike  2023-01-25 10:49:01 2023-01-25 10:58:22
 9 34EAB943F88C4C5D electric_bike 2023-01-25 20:49:47 2023-01-25 21:02:14
10 BC8AB1AA51DA9115 classic_bike  2023-01-06 16:37:19 2023-01-06 16:49:52
# ℹ 4,331,697 more rows
# ℹ 10 more variables: start_station_name &lt;chr&gt;, start_station_id &lt;chr&gt;,
#   end_station_name &lt;chr&gt;, end_station_id &lt;chr&gt;, start_lat &lt;dbl&gt;,
#   start_lng &lt;dbl&gt;, end_lat &lt;dbl&gt;, end_lng &lt;dbl&gt;, member_casual &lt;chr&gt;,
#   trip_time &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Files in ~/tripdata:  

 tripdata/part-0.parquet</code></pre>
</div>
</div>
<p>We started with 5,719,877 observations (obs) for dates spanning January to December, 2023, then removed 1,388,170 incomplete obs.</p>
<p>Of the other columns, it seems that the start_time, end_time, start_station, and end_station could show if there are possibly hidden duplicated observations. Those 4 variables combined results in the most granular view of any one observation. Meaning, that data would naturally only have duplicates in error.</p>
<p>I assumed that having the same times/dates and stations for two different ride IDs was a mistake. Although, I do not know how that error would happen. I could have assumed one person could check out multiple bikes at once. In that instance, each bike could be assigned a unique ride_id. That, however, has only happened 18 times over a year. Since it’s only one copy every time, that also raises a red flag. I did not notice any other correlations with station_id/name, member_casual, or ride_type for those particular duplicated data.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> Distinct copy count of dupes:  2 

 Total observations that have and are duplicates:  36</code></pre>
</div>
</div>
<p>By applying distinct() on dupeTable, we see the only distinct value is 2. We can safely conclude that, of the duplicates, each has a minimum and maximum of 1 extra copy.</p>
<p>Number of rows in the dupeTable is 36. Because each duplicated observation has one duplicate (n = 2), expected removed nobs is 18. The issue is that we need to get rid of not all 36 rows, but just the 1 extra duplicate observation from each, resulting in the expected 18.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Count of distinct observations:  18</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Count of distinct observations:  18</code></pre>
</div>
</div>
<p>The count of observed distinct values for the un-duplicated table was indeed 18. So now, it is time to run a count of how rows/observations are in the dataset. There is a difference, though, concerning the correct amount.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  `Original Obs` `Uncorrected Complete Obs` Corrected Complete O…¹ `Removed Obs`
           &lt;int&gt;                      &lt;int&gt;                  &lt;int&gt;         &lt;int&gt;
1        5719877                    4331707                4331689            18
# ℹ abbreviated name: ¹​`Corrected Complete Obs`</code></pre>
</div>
</div>
<p>The incorrect number of observations (nobs) was 4,331,707. The correct nobs after removing duplicated obs was 4,331,689. In short, 18 additional obs were removed.</p>
<p>Noting that it was useful for me to retain certain rows at first to determine if there were duplicates.</p>
</section>
<section id="filtering-data-smartly" class="level2">
<h2 class="anchored" data-anchor-id="filtering-data-smartly">Filtering Data, Smartly</h2>
<p>To ensure the conclusions are accurate, outliers should be filtered. Negative and very low trip times might skew trends. The underlying reason for very low trip times is somewhat of an unknown. Perhaps people often change their minds?</p>
<p>Writing the Filtered Parquet File</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># Source:   table&lt;fltrd_tripData&gt; [?? x 16]
# Database: DuckDB v0.9.2 [unknown@Linux 6.5.0-1016-azure:R 4.2.0/:memory:]
   ride_id          rideable_type started_at          ended_at           
   &lt;chr&gt;            &lt;chr&gt;         &lt;dttm&gt;              &lt;dttm&gt;             
 1 8FBD2AD70B0F6A6F classic_bike  2023-01-01 00:04:07 2023-01-01 00:13:56
 2 F9EA7B9E6C243CFC classic_bike  2023-01-01 00:04:54 2023-01-01 00:31:52
 3 27C2A67184C49D01 electric_bike 2023-01-01 00:05:43 2023-01-01 00:21:37
 4 544EFA0F99CA9099 electric_bike 2023-01-01 00:09:33 2023-01-01 00:14:21
 5 4BA829307ABF42BA classic_bike  2023-01-01 00:09:53 2023-01-01 00:25:01
 6 346B9700826F9746 classic_bike  2023-01-01 00:10:45 2023-01-01 00:18:23
 7 DA3FA50BB5A26A47 electric_bike 2023-01-01 00:11:44 2023-01-01 00:18:33
 8 0EE9294767228388 classic_bike  2023-01-01 00:11:53 2023-01-01 00:21:22
 9 049B5478C03BA915 classic_bike  2023-01-01 00:11:59 2023-01-01 00:21:34
10 080D40AFF69CBC91 classic_bike  2023-01-01 00:12:40 2023-01-01 00:18:42
# ℹ more rows
# ℹ 12 more variables: start_station_name &lt;chr&gt;, start_station_id &lt;chr&gt;,
#   end_station_name &lt;chr&gt;, end_station_id &lt;chr&gt;, start_lat &lt;dbl&gt;,
#   start_lng &lt;dbl&gt;, end_lat &lt;dbl&gt;, end_lng &lt;dbl&gt;, member_casual &lt;chr&gt;,
#   trip_time &lt;dbl&gt;, miles &lt;dbl&gt;, mph &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bikeShare_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bikeShare_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="visualizations" class="level2">
<h2 class="anchored" data-anchor-id="visualizations">Visualizations</h2>
<p>for quick reference with using Tsibble syntax</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bikeShare_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bikeShare_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bikeShare_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bikeShare_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bikeShare_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bikeShare_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="section" class="level2">




</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-average2024" class="csl-entry" role="listitem">
<span>“Average Bicycle Speed <span></span> How Fast Do Cyclists Ride and What Affects Their Pace - BikingulTimate.com (UPDATE 👍).”</span> 2024. <a href="https://bikingultimate.com/average-bicycle-speed-how-fast-do-cyclists-ride-and-what-affects-their-pace/">https://bikingultimate.com/average-bicycle-speed-how-fast-do-cyclists-ride-and-what-affects-their-pace/</a>.
</div>
<div id="ref-datalic" class="csl-entry" role="listitem">
<span>“Data License Agreement | Divvy Bikes.”</span> n.d. <a href="https://divvybikes.com/data-license-agreement">https://divvybikes.com/data-license-agreement</a>.
</div>
<div id="ref-great-ci" class="csl-entry" role="listitem">
<span>“Great-Circle Distance - Wikipedia.”</span> n.d. <a href="https://en.wikipedia.org/wiki/Great-circle_distance">https://en.wikipedia.org/wiki/Great-circle_distance</a>.
</div>
<div id="ref-indexof" class="csl-entry" role="listitem">
<span>“Index of Bucket <span>"</span>Divvy-Tripdata<span>"</span>.”</span> n.d. <a href="https://divvy-tripdata.s3.amazonaws.com/index.html">https://divvy-tripdata.s3.amazonaws.com/index.html</a>.
</div>
<div id="ref-motivate" class="csl-entry" role="listitem">
<span>“MOTIVATE.”</span> n.d. <a href="https://motivateco.com/">https://motivateco.com/</a>.
</div>
<div id="ref-rforda" class="csl-entry" role="listitem">
<span>“R for Data Science (2e) - 22&nbsp; Arrow.”</span> n.d. <a href="https://r4ds.hadley.nz/arrow">https://r4ds.hadley.nz/arrow</a>.
</div>
<div id="ref-whyduck" class="csl-entry" role="listitem">
<span>“Why DuckDB.”</span> n.d. <a href="https://duckdb.org/why_duckdb.html">https://duckdb.org/why_duckdb.html</a>.
</div>
</div></section><section class="quarto-appendix-contents" id="quarto-copyright"><h2 class="anchored quarto-appendix-heading">Copyright</h2><div class="quarto-appendix-contents"><div>Eric Mossotti</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ericMossotti\.github\.io\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>